<?php

namespace VehicleManagement\ManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicingRepository extends EntityRepository
{
	
	public function getObjects($nbLinePerPage, $offset,$user) {
		$qb = $this->createQueryBuilder('s')
		->leftJoin('s.vehicle', 'v')
		->where('v.user = :user')
		->setParameter('user', $user)
		->addSelect('v')
		->orderBy('s.date','DESC')
		->setFirstResult($offset)
		->setMaxResults($nbLinePerPage);
	
		return $qb->getQuery()
		->getResult();
	}
	
	public function getTotal($user) {
		$qb = $this->createQueryBuilder('s')
		->select('COUNT(s)')
		->leftJoin('s.vehicle','v')
		->where('v.user = :user')
		->setParameter('user', $user);
	
		return (int) $qb->getQuery()
		->getSingleScalarResult();
	}
}